# Generated by Django 5.2.1 on 2025-05-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_headerbanner_show_on_homepage_headerbanner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.CharField(blank=True, help_text="Скрытые ключевые слова для поиска (например, 'кроссовки адидас', 'джинсы синие')", max_length=500, verbose_name='Ключевые слова для поиска'),
        ),
    ]
